version: "3.4"

services:
  snippetdb:
    image: postgres
    container_name: "snippetdb"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=snippetbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zhakoboss
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  snippet.web:
    build: .
    container_name: "snippet.web"
    environment:
      - DB_PASSWORD=zhakoboss
      - DB_DB=snippetbox
      - DB_HOST=db
      - DB_TABLE=snippets
      - DB_PORT=5432
    ports:
      - '4000:4000'
    depends_on:
      - snippetdb
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge